import type { Booking, Dispute, Truck, User } from "./types";

export const seedUsers: User[] = [
  {
    id: "u-importer",
    name: "Jeanine Uwase",
    email: "jeanine@importco.rw",
    phone: "+250 788 441 220",
    role: "IMPORTER",
    location: "Kigali",
    active: true,
    company: "Uwase Import Co.",
    photo: "/photos/ibanga-importer-jeanine.png",
  },
  {
    id: "u-importer-2",
    name: "David Okello",
    email: "david@okellocargo.ug",
    phone: "+256 772 118 904",
    role: "IMPORTER",
    location: "Kampala",
    active: true,
    company: "Okello Cargo",
    photo: "/photos/ibanga-importer-david.png",
  },
  {
    id: "u-owner",
    name: "Eric Ndayisaba",
    email: "eric@ndayitrans.rw",
    phone: "+250 789 330 112",
    role: "TRUCK_OWNER",
    location: "Kigali",
    active: true,
    company: "Ndayi Transport",
    photo: "/photos/ibanga-owner-eric.png",
  },
  {
    id: "u-owner-2",
    name: "Amina Hassan",
    email: "amina@coastalhaul.ke",
    phone: "+254 722 556 018",
    role: "TRUCK_OWNER",
    location: "Mombasa",
    active: true,
    company: "Coastal Haul",
    photo: "/photos/ibanga-owner-amina.png",
  },
  {
    id: "u-admin",
    name: "Claire Mugisha",
    email: "admin@ibanga.com",
    phone: "+250 780 000 001",
    role: "ADMIN",
    location: "Kigali",
    active: true,
    company: "iBanga",
    photo: "/photos/ibanga-admin-claire.png",
  },
];

export const seedTrucks: Truck[] = [
  {
    id: "t1",
    ownerId: "u-owner",
    plateNumber: "RAD 452 C",
    truckType: "Container",
    capacity: "28 tons",
    currentLocation: "Kigali",
    preferredRoute: "Kigali — Mombasa",
    description:
      "40ft container truck, regularly runs the Northern Corridor. Good for general imported goods.",
    status: "UNAVAILABLE",
    photos: [
      "/photos/ibanga-container-highway.png",
      "/photos/ibanga-container-yard.png",
    ],
  },
  {
    id: "t2",
    ownerId: "u-owner",
    plateNumber: "RAD 118 B",
    truckType: "Refrigerated",
    capacity: "18 tons",
    currentLocation: "Musanze",
    preferredRoute: "Kigali — Kampala",
    description:
      "Cold-chain truck for produce and pharmaceuticals. Temperature logs available on request.",
    status: "UNAVAILABLE",
    photos: ["/photos/ibanga-reefer.png"],
  },
  {
    id: "t3",
    ownerId: "u-owner-2",
    plateNumber: "KCD 903 A",
    truckType: "Flatbed",
    capacity: "30 tons",
    currentLocation: "Mombasa",
    preferredRoute: "Mombasa — Kigali",
    description:
      "Flatbed with chains and tarpaulin. Ideal for machinery, steel, and oversized crates.",
    status: "AVAILABLE",
    photos: ["/photos/ibanga-flatbed.png", "/photos/ibanga-container-yard.png"],
  },
  {
    id: "t4",
    ownerId: "u-owner-2",
    plateNumber: "KCA 220 T",
    truckType: "Tanker",
    capacity: "32,000 L",
    currentLocation: "Nairobi",
    preferredRoute: "Nairobi — Kigali",
    description: "Fuel and liquid cargo tanker. Certified hoses and valves.",
    status: "UNAVAILABLE",
    photos: ["/photos/ibanga-tanker.png"],
  },
  {
    id: "t5",
    ownerId: "u-owner",
    plateNumber: "RAE 671 D",
    truckType: "Box truck",
    capacity: "8 tons",
    currentLocation: "Kigali",
    preferredRoute: "Kigali — Rusumo",
    description: "Covered box truck for packaged goods and last-mile from the border.",
    status: "UNAVAILABLE",
    photos: ["/photos/ibanga-box.png"],
  },
  {
    id: "t6",
    ownerId: "u-owner-2",
    plateNumber: "KBB 441 M",
    truckType: "Semi-trailer",
    capacity: "34 tons",
    currentLocation: "Dar es Salaam",
    preferredRoute: "Dar es Salaam — Kigali",
    description: "Long-haul semi for containerized imports from the port.",
    status: "AVAILABLE",
    photos: ["/photos/ibanga-semi.png", "/photos/ibanga-container-highway.png"],
  },
];

export const seedBookings: Booking[] = [
  {
    id: "b1",
    truckId: "t1",
    importerId: "u-importer",
    cargoType: "General cargo",
    cargoDescription: "Two 20ft containers of household electronics",
    cargoWeight: "16 tons",
    pickupLocation: "Kigali dry port",
    destination: "Mombasa port",
    pickupDate: "2026-09-08",
    expectedDeliveryDate: "2026-09-12",
    additionalInstructions: "Need evening loading. Call before arrival.",
    agreedPrice: "",
    status: "PENDING",
    createdAt: "2026-09-04T08:12:00.000Z",
  },
  {
    id: "b2",
    truckId: "t2",
    importerId: "u-importer",
    cargoType: "Perishables",
    cargoDescription: "Chilled avocados for export packing",
    cargoWeight: "12 tons",
    pickupLocation: "Musanze",
    destination: "Kampala",
    pickupDate: "2026-09-05",
    expectedDeliveryDate: "2026-09-06",
    additionalInstructions: "Keep 4–6°C.",
    agreedPrice: "RWF 850,000",
    status: "IN_PROGRESS",
    createdAt: "2026-09-03T14:40:00.000Z",
  },
  {
    id: "b3",
    truckId: "t5",
    importerId: "u-importer-2",
    cargoType: "Building materials",
    cargoDescription: "Tiles and fittings",
    cargoWeight: "7 tons",
    pickupLocation: "Kigali",
    destination: "Rusumo",
    pickupDate: "2026-09-02",
    expectedDeliveryDate: "2026-09-03",
    additionalInstructions: "",
    agreedPrice: "RWF 220,000",
    status: "DISPUTED",
    createdAt: "2026-09-01T10:00:00.000Z",
  },
  {
    id: "b4",
    truckId: "t3",
    importerId: "u-importer",
    cargoType: "Machinery",
    cargoDescription: "Generator and spare parts",
    cargoWeight: "9 tons",
    pickupLocation: "Mombasa",
    destination: "Kigali",
    pickupDate: "2026-08-20",
    expectedDeliveryDate: "2026-08-24",
    additionalInstructions: "",
    agreedPrice: "USD 1,400",
    status: "COMPLETED",
    createdAt: "2026-08-18T09:00:00.000Z",
  },
  {
    id: "b5",
    truckId: "t4",
    importerId: "u-importer-2",
    cargoType: "Packaged goods",
    cargoDescription: "Retail stock",
    cargoWeight: "10 tons",
    pickupLocation: "Nairobi",
    destination: "Kigali",
    pickupDate: "2026-09-10",
    expectedDeliveryDate: "2026-09-13",
    additionalInstructions: "Gate pass under Okello Cargo.",
    agreedPrice: "USD 980",
    status: "DELIVERED",
    createdAt: "2026-09-02T16:20:00.000Z",
  },
];

export const seedDisputes: Dispute[] = [
  {
    id: "d1",
    bookingId: "b3",
    raisedBy: "u-importer-2",
    reason: "Three crates arrived opened and 40 tiles were broken.",
    status: "OPEN",
    resolutionNotes: "",
    createdAt: "2026-09-03T11:15:00.000Z",
  },
];
